version: 2

sources:
  - name: dbt_artifacts
    database: "{% if target.type not in ('spark', 'databricks') %}{{ var('dbt_artifacts_database', target.database) }}{% endif %}"
    schema: "{{ var('dbt_artifacts_schema', target.schema) }}"
    tables:
      - name: model_executions
        identifier: "{{ var('dbt_model_executions_table', 'model_executions') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: compile_started_at
          description: '{{ doc("compile_started_at") }}'
        - name: materialization
          description: '{{ doc("materialization") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: query_completed_at
          description: '{{ doc("query_completed_at") }}'
        - name: rows_affected
          description: '{{ doc("rows_affected") }}'
        - name: schema
          description: '{{ doc("schema") }}'
        - name: status
          description: '{{ doc("status") }}'
        - name: thread_id
          description: '{{ doc("thread_id") }}'
        - name: total_node_runtime
          description: '{{ doc("total_node_runtime") }}'
        - name: was_full_refresh
          description: '{{ doc("was_full_refresh") }}'

      - name: tests
        identifier: "{{ var('dbt_tests_table', 'tests') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: depends_on_nodes
          description: '{{ doc("depends_on_nodes") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: package_name
          description: '{{ doc("package_name") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: tags
          description: '{{ doc("tags") }}'
        - name: test_path
          description: '{{ doc("test_path") }}'

      - name: test_executions
        identifier: "{{ var('dbt_test_executions_table', 'test_executions') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: compile_started_at
          description: '{{ doc("compile_started_at") }}'
        - name: failures
          description: '{{ doc("failures") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: query_completed_at
          description: '{{ doc("query_completed_at") }}'
        - name: rows_affected
          description: '{{ doc("rows_affected") }}'
        - name: status
          description: '{{ doc("status") }}'
        - name: thread_id
          description: '{{ doc("thread_id") }}'
        - name: total_node_runtime
          description: '{{ doc("total_node_runtime") }}'
        - name: was_full_refresh
          description: '{{ doc("was_full_refresh") }}'

      - name: models
        identifier: "{{ var('dbt_models_table', 'models') }}"
        columns:
        - name: checksum
          description: '{{ doc("checksum") }}'
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: database
          description: '{{ doc("database") }}'
        - name: depends_on_nodes
          description: '{{ doc("depends_on_nodes") }}'
        - name: materialization
          description: '{{ doc("materialization") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: package_name
          description: '{{ doc("package_name") }}'
        - name: path
          description: '{{ doc("path") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: schema
          description: '{{ doc("schema") }}'

      - name: seeds
        identifier: "{{ var('dbt_seeds_table', 'seeds') }}"
        columns:
        - name: checksum
          description: '{{ doc("checksum") }}'
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: database
          description: '{{ doc("database") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: package_name
          description: '{{ doc("package_name") }}'
        - name: path
          description: '{{ doc("path") }}'
        - name: schema
          description: '{{ doc("schema") }}'

      - name: seed_executions
        identifier: "{{ var('dbt_seed_executions_table', 'seed_executions') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: compile_started_at
          description: '{{ doc("compile_started_at") }}'
        - name: materialization
          description: '{{ doc("materialization") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: query_completed_at
          description: '{{ doc("query_completed_at") }}'
        - name: rows_affected
          description: '{{ doc("rows_affected") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: schema
          description: '{{ doc("schema") }}'
        - name: status
          description: '{{ doc("status") }}'
        - name: thread_id
          description: '{{ doc("thread_id") }}'
        - name: total_node_runtime
          description: '{{ doc("total_node_runtime") }}'
        - name: was_full_refresh
          description: '{{ doc("was_full_refresh") }}'

      - name: exposures
        identifier: "{{ var('dbt_exposures_table', 'exposures') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: depends_on_nodes
          description: '{{ doc("depends_on_nodes") }}'
        - name: description
          description: '{{ doc("description") }}'
        - name: maturity
          description: '{{ doc("maturity") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: owner
          description: '{{ doc("owner") }}'
        - name: package_name
          description: '{{ doc("package_name") }}'
        - name: path
          description: '{{ doc("path") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: type
          description: '{{ doc("type") }}'
        - name: url
          description: '{{ doc("url") }}'

      - name: snapshots
        identifier: "{{ var('dbt_snapshots_table', 'snapshots') }}"
        columns:
        - name: checksum
          description: '{{ doc("checksum") }}'
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: database
          description: '{{ doc("database") }}'
        - name: depends_on_nodes
          description: '{{ doc("depends_on_nodes") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: package_name
          description: '{{ doc("package_name") }}'
        - name: path
          description: '{{ doc("path") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: schema
          description: '{{ doc("schema") }}'
        - name: strategy
          description: '{{ doc("strategy") }}'

      - name: snapshot_executions
        identifier: "{{ var('dbt_snapshot_executions_table', 'snapshot_executions') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: compile_started_at
          description: '{{ doc("compile_started_at") }}'
        - name: materialization
          description: '{{ doc("materialization") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: query_completed_at
          description: '{{ doc("query_completed_at") }}'
        - name: rows_affected
          description: '{{ doc("rows_affected") }}'
        - name: schema
          description: '{{ doc("schema") }}'
        - name: status
          description: '{{ doc("status") }}'
        - name: thread_id
          description: '{{ doc("thread_id") }}'
        - name: total_node_runtime
          description: '{{ doc("total_node_runtime") }}'
        - name: was_full_refresh
          description: '{{ doc("was_full_refresh") }}'

      - name: sources
        identifier: "{{ var('dbt_sources_table', 'sources') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: database
          description: '{{ doc("database") }}'
        - name: freshness
          description: '{{ doc("freshness") }}'
        - name: identifier
          description: '{{ doc("identifier") }}'
        - name: loaded_at_field
          description: '{{ doc("loaded_at_field") }}'
        - name: loader
          description: '{{ doc("loader") }}'
        - name: name
          description: '{{ doc("name") }}'
        - name: node_id
          description: '{{ doc("node_id") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: schema
          description: '{{ doc("schema") }}'
        - name: source_name
          description: '{{ doc("source_name") }}'

      - name: invocations
        identifier: "{{ var('dbt_invocations_table', 'invocations') }}"
        columns:
        - name: command_invocation_id
          description: '{{ doc("command_invocation_id") }}'
        - name: dbt_version
          description: '{{ doc("dbt_version") }}'
        - name: project_name
          description: '{{ doc("project_name") }}'
        - name: run_started_at
          description: '{{ doc("run_started_at") }}'
        - name: dbt_command
          description: '{{ doc("dbt_command") }}'
        - name: full_refresh_flag
          description: '{{ doc("full_refresh_flag") }}'
        - name: target_profile_name
          description: '{{ doc("target_profile_name") }}'
        - name: target_name
          description: '{{ doc("target_name") }}'
        - name: target_schema
          description: '{{ doc("target_schema") }}'
        - name: target_threads
          description: '{{ doc("target_threads") }}'
        - name: dbt_cloud_project_id
          description: '{{ doc("dbt_cloud_project_id") }}'
        - name: dbt_cloud_job_id
          description: '{{ doc("dbt_cloud_job_id") }}'
        - name: dbt_cloud_run_id
          description: '{{ doc("dbt_cloud_run_id") }}'
        - name: dbt_cloud_run_reason_category
          description: '{{ doc("dbt_cloud_run_reason_category") }}'
        - name: dbt_cloud_run_reason
          description: '{{ doc("dbt_cloud_run_reason") }}'
        - name: env_vars
          description: '{{ doc("env_vars") }}'
        - name: dbt_vars
          description: '{{ doc("dbt_vars") }}'
